
package com.scoreservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScoreService", targetNamespace = "http://scoreservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScoreService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fixScore", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.FixScore")
    @ResponseWrapper(localName = "fixScoreResponse", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.FixScoreResponse")
    @Action(input = "http://scoreservice.com/ScoreService/fixScoreRequest", output = "http://scoreservice.com/ScoreService/fixScoreResponse")
    public String fixScore(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteScore", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.DeleteScore")
    @ResponseWrapper(localName = "deleteScoreResponse", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.DeleteScoreResponse")
    @Action(input = "http://scoreservice.com/ScoreService/deleteScoreRequest", output = "http://scoreservice.com/ScoreService/deleteScoreResponse")
    public String deleteScore(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScore", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.GetScore")
    @ResponseWrapper(localName = "getScoreResponse", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.GetScoreResponse")
    @Action(input = "http://scoreservice.com/ScoreService/getScoreRequest", output = "http://scoreservice.com/ScoreService/getScoreResponse")
    public String getScore(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClassAverage", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.GetClassAverage")
    @ResponseWrapper(localName = "getClassAverageResponse", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.GetClassAverageResponse")
    @Action(input = "http://scoreservice.com/ScoreService/getClassAverageRequest", output = "http://scoreservice.com/ScoreService/getClassAverageResponse")
    public String getClassAverage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addScore", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.AddScore")
    @ResponseWrapper(localName = "addScoreResponse", targetNamespace = "http://scoreservice.com/", className = "com.scoreservice.AddScoreResponse")
    @Action(input = "http://scoreservice.com/ScoreService/addScoreRequest", output = "http://scoreservice.com/ScoreService/addScoreResponse")
    public String addScore(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
